top_title       = "My Resume"
title           = "My Expertises"
subtitle        = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore"
second_subtitle = "Magna aliquyam erat, sed diam voluptua. At vero eos accusam justo."
educations_tab = "Educations"
experiences_tab = "Experiences"

[[educations]]
title   = "Master in Arts"
content = "Lorem ipsum dolor sit amet conset sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam"
time    = "2008-2010"
  
[[educations]]
title   = "Master in Arts"
content = "Lorem ipsum dolor sit amet conset sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam"
time    = "2008-2010"

[[educations]]
title   = "Master in Arts"
content = "Lorem ipsum dolor sit amet conset sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam"
time    = "2008-2010"

[[educations]]
title   = "Master in Arts"
content = "Lorem ipsum dolor sit amet conset sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam"
time    = "2008-2010"

[[educations]]
title   = "Master in Arts"
content = "Lorem ipsum dolor sit amet conset sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam"
time    = "2008-2010"

[[experiences]]
title   = "experience"
content = "Lorem ipsum dolor sit amet conset sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam"
time    = "2008-2010"

[[experiences]]
title   = "experience"
content = "Lorem ipsum dolor sit amet conset sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam"
time    = "2008-2010"

[[experiences]]
title   = "experience"
content = "Lorem ipsum dolor sit amet conset sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam"
time    = "2008-2010"

[[experiences]]
title   = "experience"
content = "Lorem ipsum dolor sit amet conset sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam"
time    = "2008-2010"

[[experiences]]
title   = "experience"
content = "Lorem ipsum dolor sit amet conset sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam"
time    = "2008-2010"
