top_title       = "Mon CV"
title           = "Mes expertises"
subtitle        = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore"
second_subtitle = "Magna aliquyam erat, sed diam voluptua. At vero eos accusam justo."
educations_tab  = "Éducation"
experiences_tab = "Expériences"

[[educations]]
title   = "Master en Arts"
content = "Lorem ipsum dolor sit amet conset sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam"
time    = "2008-2010"

[[educations]]
title   = "Master en Arts"
content = "Lorem ipsum dolor sit amet conset sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam"
time    = "2008-2010"

[[educations]]
title   = "Master en Arts"
content = "Lorem ipsum dolor sit amet conset sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam"
time    = "2008-2010"

[[educations]]
title   = "Master en Arts"
content = "Lorem ipsum dolor sit amet conset sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam"
time    = "2008-2010"

[[educations]]
title   = "Master en Arts"
content = "Lorem ipsum dolor sit amet conset sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam"
time    = "2008-2010"

[[experiences]]
title   = "Expérience"
content = "Lorem ipsum dolor sit amet conset sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam"
time    = "2008-2010"

[[experiences]]
title   = "Expérience"
content = "Lorem ipsum dolor sit amet conset sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam"
time    = "2008-2010"

[[experiences]]
title   = "Expérience"
content = "Lorem ipsum dolor sit amet conset sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam"
time    = "2008-2010"

[[experiences]]
title   = "Expérience"
content = "Lorem ipsum dolor sit amet conset sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam"
time    = "2008-2010"

[[experiences]]
title   = "Expérience"
content = "Lorem ipsum dolor sit amet conset sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam"
time    = "2008-2010"
