# The URL the site will be built for
base_url = "http://127.0.0.1:1111"

#
minify_html = true

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

#
default_language = "fr"

[languages.en]
title = "Portio Zola"
generate_feeds = true
build_search_index = false

taxonomies = [
    { name = "tags", feed = true, render = true, paginate_by = 9 },
    { name = "categories", feed = true, render = true, paginate_by = 9 },
]

[languages.en.translations]
contact_me = "Contact me"
start_project = "Let's Start a Project"
showing_all = "Showing All"
hire_me_now = "Hire Me Now"
get_in_touch = "Get in touch"
see_details = "See Details"
sitemap = "Sitemap"
address = "Address"
phone = "Téléphone"
email = "Email"
categories_description = "Showing all posts with the category"
tags_description = "Showing all posts with the tag"
opening_hours = "Working hours"
form_title = "Contact form"
form_button = "Send Message"
form_input_name = "Name"
form_input_email = "Email"
form_input_message = "Message"
form_input_agreement = "I agree that my submitted data is being collected and stored."
copyright = "All right reserved copyright © Portio 2020"

# Menus
home = "Home"
about = "About"
service = "Service"
work = "Work"
resume = "Resume"
blog = "Blog"
contact = "Contact"

# Sitemaps
about_me = "About me"
frequently_ask_question = "Frequently Ask Question"
privacy_and_policy = "Privacy & Policy"
latest_article = "Latest Article"

[languages.fr]
title = "Portio Zola"
generate_feeds = true
build_search_index = false

taxonomies = [
    { name = "tags", feed = true, render = true, paginate_by = 9 },
    { name = "categories", feed = true, render = true, paginate_by = 9 },
]

[languages.fr.translations]
contact_me   = "Contactez‑moi"
start_project = "Commencer un projet"
showing_all = "Afficher tout"
hire_me_now = "Engagez‑moi maintenant"
get_in_touch = "Entrer en contact"
see_details = "Voir les détails"
sitemap = "Plan du site"
address = "Adresse"
phone = "Téléphone"
email = "E‑mail"
categories_description = "Affichage de tous les articles de la catégorie"
tags_description = "Affichage de tous les articles du tag"
opening_hours = "Horaires d'ouverture"
form_title = "Formulaire de contact"
form_button = "Envoyer le message"
form_input_name = "Nom"
form_input_email = "E‑mail"
form_input_message = "Message"
form_input_agreement = "J’accepte que mes données soumises soient collectées et stockées."
copyright = "Tous droits réservés © Portio 2020"

# Menus
home = "Accueil"
about = "À propos"
service = "Services"
work = "Réalisations"
resume = "CV"
blog = "Blog"
contact = "Contact"

# Sitemaps
about_me = "À propos de moi"
frequently_ask_question = "Foire aux questions"
privacy_and_policy = "Politique de confidentialité"
latest_article = "Dernier article"


[extra]
date_format = "%d %B, %Y"
logo = "images/logo.png"
footer_logo = "images/logo.png"
# google_analytics = "YOUR TOKEN FOR GOOGLE ANALYTICS"
formspree_url = "YOUR FORMSPREE URL"
display_cta = true

menus = [
  { name = "home", url = "#home" },
  { name = "about", url = "#about" },
  { name = "service", url = "#service" },
  { name = "work", url = "#portfolio" },
  { name = "resume", url = "#resume" },
  { name = "blog", url = "#blog" },
  { name = "contact", url = "#contact" }
]

sitemaps = [
  { name = "about_me", url = "#about" },
  { name = "frequently_ask_question", url = "#" },
  { name = "privacy_and_policy", url = "#" },
  { name = "latest_article", url = "#" }
]

socials = [
  { icon = "facebook-original", url = "https://www.facebook.com/" },
  { icon = "linkedin-original", url = "https://www.linkedin.com/" },
  { icon = "pinterest", url = "https://www.pinterest.com" },
  { icon = "twitter-original",  url = "https://www.twitter.com" }
]

[extra.address]
phone = "+(448) 833 5272 332"
email = "hello@example.com"
address = "23 Khan Niketon, Grand Street, NYK."
opening_hours = "Open from 10am to 6pm (close at 5pm Sundays) "

[extra.map]
latitude = "48.864716"
longitude = "2.349014"
