# The URL the site will be built for
base_url = "https://satyajitpuhan.github.io/"

#
minify_html = true

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

#
default_language = "en"

[languages.en]
title = "Satyajit Puhan"
generate_feeds = true
build_search_index = false

taxonomies = [
    { name = "tags", feed = true, render = true, paginate_by = 9 },
    { name = "categories", feed = true, render = true, paginate_by = 9 },
]

[languages.en.translations]
contact_me = "Contact Me"
start_project = "Get In Touch"
showing_all = "Showing All"
hire_me_now = "Contact Me"
get_in_touch = "Get in Touch"
see_details = "See Details"
sitemap = "Sitemap"
address = "Address"
phone = "Phone"
email = "Email"
categories_description = "Showing all posts with the category"
tags_description = "Showing all posts with the tag"
opening_hours = "Working Hours"
form_title = "Contact Form"
form_button = "Send Message"
form_input_name = "Name"
form_input_email = "Email"
form_input_message = "Message"
form_input_agreement = "I agree that my submitted data is being collected and stored."
copyright = "All rights reserved © Satyajit Puhan 2026"

# Menus
home = "Home"
about = "About"
service = "Research"
work = "Publications"
resume = "Resume"
blog = "Talks"
contact = "Contact"

# Sitemaps
about_me = "About Me"
frequently_ask_question = "Research"
privacy_and_policy = "Publications"
latest_article = "Latest Talks"


[languages.or]
title = "ସତ୍ୟଜିତ ପୁହାଣ"
generate_feeds = true
build_search_index = false

taxonomies = [
    { name = "tags", feed = true, render = true, paginate_by = 9 },
    { name = "categories", feed = true, render = true, paginate_by = 9 },
]

[languages.or.translations]
contact_me = "ମୋ ସହିତ ଯୋଗାଯୋଗ କରନ୍ତୁ"
start_project = "ଯୋଗାଯୋଗ କରନ୍ତୁ"
showing_all = "ସମସ୍ତ ଦେଖାଉଛି"
hire_me_now = "ଯୋଗାଯୋଗ କରନ୍ତୁ"
get_in_touch = "ଯୋଗାଯୋଗ କରନ୍ତୁ"
see_details = "ବିବରଣୀ ଦେଖନ୍ତୁ"
sitemap = "ସାଇଟମ୍ୟାପ୍"
address = "ଠିକଣା"
phone = "ଫୋନ୍"
email = "ଇମେଲ୍"
categories_description = "ଶ୍ରେଣୀ ସହିତ ସମସ୍ତ ପୋଷ୍ଟଗୁଡିକ ଦେଖାଉଛି"
tags_description = "ଟ୍ୟାଗ୍ ସହିତ ସମସ୍ତ ପୋଷ୍ଟଗୁଡିକ ଦେଖାଉଛି"
opening_hours = "କାର୍ଯ୍ୟ ସମୟ"
form_title = "ଯୋଗାଯୋଗ ଫର୍ମ"
form_button = "ମେସେଜ୍ ପଠାନ୍ତୁ"
form_input_name = "ନାମ"
form_input_email = "ଇମେଲ୍"
form_input_message = "ମେସେଜ୍"
form_input_agreement = "ମୋର ଦାଖଲ ହୋଇଥିବା ଡାଟା ସଂଗ୍ରହ ଓ ସଂରକ୍ଷଣ କରାଯାଉଥିବାରୁ ମୁଁ ସମ୍ମତ ଅଟେ।"
copyright = "ସର୍ବସତ୍ତ୍ୱ ସଂରକ୍ଷିତ © ସତ୍ୟଜିତ ପୁହାଣ 2026"

# Menus
home = "ମୁଖ୍ୟ ପୃଷ୍ଠା"
about = "ମୋ ବିଷୟରେ"
service = "ଗବେଷଣା"
work = "ପ୍ରକାଶନ"
resume = "ବାୟୋଡାଟା"
blog = "ଆଲୋଚନା"
contact = "ଯୋଗାଯୋଗ"

# Sitemaps
about_me = "ମୋ ବିଷୟରେ"
frequently_ask_question = "ଗବେଷଣା"
privacy_and_policy = "ପ୍ରକାଶନ"
latest_article = "ଆଲୋଚନା"


[extra]
date_format = "%d %B, %Y"
logo = "images/logo.png"
footer_logo = "images/logo.png"
# google_analytics = "YOUR TOKEN FOR GOOGLE ANALYTICS"
formspree_url = "https://formspree.io/f/puhansatyajit@gmail.com"
display_cta = true

menus = [
  { name = "home", url = "#home" },
  { name = "about", url = "#about" },
  { name = "service", url = "#service" },
  { name = "work", url = "#portfolio" },
  { name = "resume", url = "#resume" },
  { name = "blog", url = "#blog" },
  { name = "contact", url = "#contact" }
]

sitemaps = [
  { name = "about_me", url = "#about" },
  { name = "frequently_ask_question", url = "#service" },
  { name = "privacy_and_policy", url = "#portfolio" },
  { name = "latest_article", url = "#blog" }
]

socials = [
  { icon = "github-original", url = "https://github.com/satyajitpuhan" },
  { icon = "linkedin-original", url = "https://www.linkedin.com/in/satyajit-puhan-b9889a162/" },
  { icon = "google-scholar", url = "https://scholar.google.com/citations?hl=en&user=pKbmhZQAAAAJ/" },
  { icon = "twitter-original", url = "https://www.researchgate.net/profile/Satyajit-Puhan/" },
  { icon = "chrome-original", url = "https://inspirehep.net/authors/2695282" },
  { icon = "facebook-original", url = "https://www.facebook.com/satyajit.puhan" },
  { icon = "google-original", url = "https://orcid.org/0009-0004-9766-5005" },
  { icon = "instagram-original", url = "https://www.instagram.com/puhan_satyaji/" }
]

[extra.address]
phone = "+91-9776342407"
email = "puhansatyajit@gmail.com | puhansatyajit1@gmail.com | satyajitp.ph.21@nitj.ac.in | bealonekrishan@gmail.com"
address = "Dr. B R Ambedkar NIT, Jalandhar, Punjab, India"
opening_hours = "Available for research collaborations"

[extra.map]
latitude = "31.3955"
longitude = "75.5354"
