top_title = ""
title = "ସହକର୍ମୀଗଣ |"
subtitle = "ଅନୁସନ୍ଧାନକାରୀ ଏବଂ ପରାମର୍ଶଦାତା ମୋର କାମ କରିବାର ସ privilege ଭାଗ୍ୟ ଅଛି |"
[[collaborators]]
name = "ଡ Har ହାର୍ଲିନ୍ ଡାହିଆ"
role = "Supervisor (PhD)"
institution = "Dr. B R Ambedkar NIT, Jalandhar"

[[collaborators]]
name = "ପ୍ରଫେସର ଓଲେଗ ଭି ଟେରିଆଭ"
role = "Supervisor (JINR)"
institution = "JINR, Dubna, Russia"

[[collaborators]]
name = "ପ୍ରଫେସର ସାବୟାସୀ ଘୋଷ"
role = "Collaborator"
institution = "IIT Bhilai, Chhattisgarh"

[[collaborators]]
name = "ପ୍ରଫେସର ଉଜୱାଲ ଲାହା"
role = "MSc Supervisor"
institution = "NIT Jamshedpur"

[[collaborators]]
name = "ପ୍ରଫେସର ଅରବିନ୍ଦ କୁମାର"
role = "Collaborator"
institution = "NIT Jalandhar"

[[collaborators]]
name = "ପ୍ରଫେସର ସୁନେଲ ଦତ୍ତ"
role = "Collaborator"
institution = "NIT Jalandhar"

[[collaborators]]
name = "ନରିନ୍ଦର କୁମାର"
role = "Collaborator"
institution = "NIT Jalandhar"

[[collaborators]]
name = "ଶୁଭମ୍ ଶର୍ମା |"
role = "Collaborator"
institution = "NIT Jalandhar"

[[collaborators]]
name = "ରିତାନସୁ ପାଣ୍ଡେ |"
role = "Collaborator"
institution = "NIT Jalandhar"

[[collaborators]]
name = "ଅନସୁ ଗ aut ତମ |"
role = "Collaborator"
institution = "NIT Jalandhar"

[[collaborators]]
name = "ତନିଷା |"
role = "Collaborator"
institution = "NIT Jalandhar"

[[collaborators]]
name = "ଆଶୁତୋଷ ଦ୍ୱିବେଦୀ |"
role = "Collaborator"
institution = "IIT Bhilai, Chhattisgarh"
image = "images/collaborators/ashutosh.jpg"

[[collaborators]]
name = "ଅନୁରାଗ ଯାଦବ |"
role = "Collaborator"
institution = "NIT Jalandhar"

[[collaborators]]
name = "ରିତୱିକ୍ ଆଚାର୍ଯ୍ୟ |"
role = "Collaborator"
institution = "NIT Jalandhar"

[[collaborators]]
name = "ହରି ଗୋବିନ୍ଦ ପି"
role = "Collaborator"
institution = "NIT Jalandhar"

[[collaborators]]
name = "ଅଭିଷେକ କେ ପି"
role = "Collaborator"
institution = "NIT Jalandhar"

