title = "ନମସ୍କାର, ମୁଁ ସତ୍ୟଜିତ୍ ପୁହାନ୍ |"
description = "# ଉଚ୍ଚ ଶକ୍ତି ପଦାର୍ଥ ବିଜ୍ଞାନରେ ଅନୁସନ୍ଧାନକାରୀ |\n\nNIT Jalandhar ର ସିନିୟର ରିସର୍ଚ୍ଚ ଫେଲୋ, ହାଲ୍ରନ୍ ର କ୍ୱାଣ୍ଟମ୍ ସ୍ଥାପତ୍ୟକୁ ହାଲୁକା ସାମ୍ମୁଖ୍ୟର ଗତିଶୀଳତା ମାଧ୍ୟମରେ ଖୋଲିଲା | ଶାରୀରିକ ସମୀକ୍ଷା D, JHEP, ଏବଂ ଅଗ୍ରଣୀ ଜର୍ଣ୍ଣାଲରେ 20+ ପ୍ରକାଶନ ସହିତ - ଏବଂ ଜାତୀୟ ମାନ୍ୟତା ** AIR-877 (JAM) ** ଏବଂ ** AIR-209 (JEST) ** - ମୁଁ EIC ଏବଂ NICA ପରି ଭବିଷ୍ୟତର ଧକ୍କାମାନଙ୍କରେ ପର୍ଯ୍ୟବେକ୍ଷଣଯୋଗ୍ୟ ମେସନ୍ ଗଠନ ସହିତ ପ୍ରଥମ ନୀତି QCD କୁ ବ୍ରିଜ୍ କରେ |"
button_name = "Contact Me"
button_url = "contact"
image = "images/hero/me1.jpg"
[[gallery]]
image = "images/gallery/switzerland-alps.jpg"
caption = "Zuoz, Swiss Alps"

[[gallery]]
image = "images/gallery/moscow-bolshoi.jpg"
caption = "Bolshoi Theatre, Moscow"

[[gallery]]
image = "images/gallery/red-square-moscow.jpg"
caption = "Red Square, Moscow"

[[gallery]]
image = "images/gallery/hanoi-airport.jpg"
caption = "Manali"

[[gallery]]
image = "images/gallery/jinr-office-dubna.jpg"
caption = "IIT Mandi"

[[gallery]]
image = "images/gallery/adiyogi-coimbatore.jpg"
caption = "Adiyogi, Coimbatore"

[[gallery]]
image = "images/gallery/hilltop-bengaluru.jpg"
caption = "Nandi Hills, Bengaluru"

[[gallery]]
image = "images/gallery/moonlit-rooftop.jpg"
caption = "BLTP, JINR Dubna"

[[gallery]]
image = "images/gallery/hilltop-sunset.jpg"
caption = "Hilltop Sunset, Dharamshala"

[[gallery]]
image = "images/gallery/office-research.jpg"
caption = "Research Lab, NIT Jalandhar"

