top_title = "My Skills"
title     = "Why hire me for your next project?"
subtitle  = "My goal is to build a strong supportive professional network among all freelancers and startups in order to improve their performance."
image     = "images/skill/skill_image.jpg"

[[skills]]
title   = "HTML"
percent = 69

[[skills]]
title   = "CSS"
percent = 60
    
[[skills]]
title   = "Javascript"
percent = 85
