top_title = "My Skills"
title     = "Research Tools & Expertise"
subtitle  = "I combine analytical techniques with computational simulations using various theoretical models, tools, and programming languages."
image     = "images/skill/skill_image.jpg"

[[skills]]
title   = "Mathematica"
percent = 92

[[skills]]
title   = "Python"
percent = 85

[[skills]]
title   = "Light-Front Quark Model"
percent = 95

[[skills]]
title   = "LHAPDF / xFitter"
percent = 80

[[skills]]
title   = "LaTeX"
percent = 90
