top_title = "Mes compétences"
title     = "Pourquoi m’engager pour votre prochain projet ?"
subtitle  = "Mon objectif est de créer un réseau professionnel solide et solidaire entre freelances et start‑ups afin d’améliorer leurs performances."
image     = "images/skill/skill_image.jpg"

[[skills]]
title   = "HTML"
percent = 69

[[skills]]
title   = "CSS"
percent = 60

[[skills]]
title   = "JavaScript"
percent = 85
