top_title = "Témoignages"
title     = "Ce que les gens disent de moi ?"

[[testimonials]]
name    = "Ryan Cook"
comment = "Takimata sanctus est lorem ipsum dolor sit amet lorem ipsum dolor sit amet consetur sad ipscing elitr sed diam nonumy eirmod tempor invidunt labore dolore magna."
time    = "Jan 20, 2020"
star    = 5

[[testimonials]]
name    = "Justin Trudo"
comment = "Takimata sanctus est lorem ipsum dolor sit amet lorem ipsum dolor sit amet consetur sad ipscing elitr sed diam nonumy eirmod tempor invidunt labore dolore magna."
time    = "Jan 16, 2020"
star    = 4

[[testimonials]]
name    = "Franky Filth"
comment = "Takimata sanctus est lorem ipsum dolor sit amet lorem ipsum dolor sit amet consetur sad ipscing elitr sed diam nonumy eirmod tempor invidunt labore dolore magna."
time    = "Mar 08, 2020"
star    = 3
