title       = "Hello, I am Satyajit Puhan"
description = """
# Researcher in High Energy Physics

Senior Research Fellow at Dr. B R Ambedkar NIT, Jalandhar. Currently a Junior Research Fellow at JINR, Dubna, Moscow. Exploring the internal structure of hadrons through light-front dynamics.
"""
button_name = "Contact Me"
button_url  = "contact"
image       = "images/hero/me1.jpg"
