title       = "Bonjour, je suis Natasha"
description = """
# Je suis là pour votre projet personnel

Profitez de la diversité des équipes et développez leurs réseaux avec d’autres personnes de divers domaines grâce à cela.
"""

button_name = "Me contacter"
button_url  = "contact"
image       = "images/hero/2960351.jpg"
video_thumb = "images/hero/popup-thumb.png"
video_url   = "https://www.youtube.com/embed/tgbNymZ7vqY"
