title = "À propos"
image = "images/about/about-img.jpg"
buttons = [ "" ]

description = """
## À propos de moi

Profitez de la diversité des équipes et développez leurs réseaux avec d’autres personnes de divers domaines grâce à ce qui est proposé.
"""

content = """
### Je conçois et crée des choses ultimes.

J’aime travailler sur la conception d’expérience utilisateur et d’interface utilisateur. Parce que j’aime résoudre les problèmes de design et trouver des solutions simples et meilleures pour les résoudre. J’essaie toujours de créer une interface utilisateur de qualité avec la meilleure expérience utilisateur. Je travaille comme designer visuel depuis.
"""
