top_title = "Zone de travail"
title     = "Services créatifs"
subtitle  = "Profitez de la diversité des équipes et développez leurs réseaux avec d’autres personnes de divers domaines grâce à cela."

[[services]]
title   = "Conception UI/UX"
content = "Lorem ipsum dolor sit amet conset sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat."
image   = "images/service/ui-ux.svg"

[[services]]
title   = "Développement Web"
content = "Lorem ipsum dolor sit amet conset sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat."
image   = "images/service/web.svg"

[[services]]
title   = "Design créatif"
content = "Lorem ipsum dolor sit amet conset sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat."
image   = "images/service/creative.svg"

[[services]]
title   = "Image de marque"
content = "Lorem ipsum dolor sit amet conset sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat."
image   = "images/service/branding.svg"

[[services]]
title   = "Conception UI/UX"
content = "Lorem ipsum dolor sit amet conset sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat."
image   = "images/service/ui-ux.svg"

[[services]]
title   = "Développement Web"
content = "Lorem ipsum dolor sit amet conset sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat."
image   = "images/service/web.svg"
